# Generated by Django 4.1.7 on 2023-05-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews_score',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
