# Generated by Django 4.1.7 on 2023-05-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_orderproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_choice',
            field=models.CharField(choices=[('D', 'Desktops'), ('M', 'Monitors'), ('L', 'Laptops'), ('Mi', 'Mice'), ('K', 'Keyboards'), ('H', 'Headsets'), ('B', 'Bags'), ('C', 'Chairs')], default='H', max_length=2),
        ),
    ]
