# Generated by Django 4.1.7 on 2023-05-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_product_quantity_orderproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_choice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
