# Generated by Django 4.1.7 on 2023-05-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='date_created',
            new_name='date_ordered',
        ),
        migrations.AddField(
            model_name='receipt',
            name='invoice_number',
            field=models.CharField(default='18', max_length=100),
            preserve_default=False,
        ),
    ]
