# Generated by Django 4.1.7 on 2023-05-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_customer_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Country',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Zip_Code',
            new_name='zipcode',
        ),
    ]
