# Generated by Django 4.1.7 on 2023-05-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_guestuser_customer_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guestuser',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guestuser',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
