# Generated by Django 4.1.7 on 2023-06-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_customer_email_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews_score',
            field=models.FloatField(),
        ),
    ]
